<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cloudinfragen" nsURI="http://www.cloudinfragen.com/metamodel"
    nsPrefix="cloudinfragen">
  <eClassifiers xsi:type="ecore:EClass" name="Infrastructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" ordered="false"
        upperBound="-1" eType="#//CloudResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CloudResource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tags" ordered="false" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputeInstance" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keypair" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="volumes" ordered="false"
        upperBound="-1" eType="#//Volume" changeable="false" eOpposite="#//Volume/attachedTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="securityGroups" ordered="false"
        upperBound="-1" eType="#//SecurityGroup" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoScalingGroup" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSize" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSize" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desiredCapacity" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" ordered="false"
        upperBound="-1" eType="#//ComputeInstance" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Volume" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encrypted" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachedTo" ordered="false"
        unique="false" eType="#//ComputeInstance" changeable="false" eOpposite="#//ComputeInstance/volumes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageBucket" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versioning" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicAccess" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileSystem" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mountPoint" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacityGB" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encrypted" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VPC" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cidrBlock" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subnets" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Subnet" containment="true" eOpposite="#//Subnet/vpc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeTables" ordered="false"
        upperBound="-1" eType="#//RouteTable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subnet" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cidr" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availabilityZone" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vpc" ordered="false" unique="false"
        lowerBound="1" eType="#//VPC" changeable="false" eOpposite="#//VPC/subnets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeTable" ordered="false"
        unique="false" eType="#//RouteTable" changeable="false" eOpposite="#//RouteTable/subnets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteTable" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routes" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subnets" ordered="false"
        upperBound="-1" eType="#//Subnet" changeable="false" eOpposite="#//Subnet/routeTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityGroup" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inboundRules" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outboundRules" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadBalancer" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoScalingGroups" ordered="false"
        upperBound="-1" eType="#//AutoScalingGroup" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" ordered="false"
        upperBound="-1" eType="#//ComputeInstance" changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subnets" ordered="false"
        upperBound="-1" eType="#//Subnet" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IAMEntity" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityType" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actions" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resources" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assumeRolePolicy" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MonitoringService" eSuperTypes="#//CloudResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metrics" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alerts" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="monitoredResources" ordered="false"
        unique="false" upperBound="-1" eType="#//CloudResource" changeable="false"/>
  </eClassifiers>
</ecore:EPackage>
